name: luacheck

on:
  push:
  pull_request:
  # allow manually starting this workflow
  workflow_dispatch:

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-20.04

    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
      - name: Run luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: lua/ modROS.lua
          annotate: warning
          # ignore vehicle_utils.lua only in the CI config (not our main
          # luacheckrc). We ignore it until we fix it (bad), but get reminded
          # about it needing fixes on every local luacheck run.
          args: --exclude-files lua/vehicle_util.lua
